// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoFOau0aX6tBlTHhWZQUVgAdec2hafy5E',
    appId: '1:813818539053:web:9cee6887f358ed5f3b1ca4',
    messagingSenderId: '813818539053',
    projectId: 'stokvelgo',
    authDomain: 'stokvelgo.firebaseapp.com',
    storageBucket: 'stokvelgo.appspot.com',
    measurementId: 'G-NQGWJYT5H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHcOty-mUZLnPgQTZJIpU_eRublg9-Ir8',
    appId: '1:813818539053:android:26b2d817799910f63b1ca4',
    messagingSenderId: '813818539053',
    projectId: 'stokvelgo',
    storageBucket: 'stokvelgo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk4yOHpyl6pm8qcT4lPbK-H3TBTI5SJiQ',
    appId: '1:813818539053:ios:72e48c9302f0ad0f3b1ca4',
    messagingSenderId: '813818539053',
    projectId: 'stokvelgo',
    storageBucket: 'stokvelgo.appspot.com',
    iosBundleId: 'com.example.stokvelGo',
  );
}
